module.exports=[
    require('./repeat'),
    require('./events'),
    require('./model'),
    require('./show-hide'),
    require('./disabled'),
    require('./src'),
    require('./active'),
    require('./data'),
];
